#!/usr/bin/env python3
"""
NanoAI v2.5 Self-Bootstrapping OS
Auto-installs dependencies, fixes itself, evolves autonomously
"""

import os
import sys
import subprocess
import importlib.util
import traceback
from pathlib import Path

class AutoBootstrap:
    def __init__(self):
        self.root = Path(__file__).parent
        self.requirements = self.root / "requirements.txt"
        self.core_dir = self.root / "core"

    def auto_install_deps(self):
        """Scan & auto-install missing packages"""
        print("🔧 Auto-Dependency Check...")
        
        if not self.requirements.exists():
            basic_reqs = ["requests", "beautifulsoup4"]
            with open(self.requirements, "w") as f:
                f.write("\n".join(basic_reqs))
        
        missing = []
        with open(self.requirements) as f:
            for pkg in f.read().splitlines():
                pkg = pkg.strip()
                if pkg and not self._is_installed(pkg):
                    missing.append(pkg)
        
        for pkg in missing:
            print(f"📦 Installing {pkg}...")
            try:
                subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", pkg])
                print(f"✅ {pkg} installed")
            except:
                print(f"⚠️ {pkg} install failed")
        
        print("✅ Dependencies ready")

    def _is_installed(self, package: str) -> bool:
        return importlib.util.find_spec(package.replace("-", "_").split("==")[0]) is not None

    def self_heal_core(self):
        """Regenerate missing core files"""
        core_files = ["brain.py", "revolver.py", "agent.py", "generator.py"]
        for core_file in core_files:
            file_path = self.core_dir / core_file
            if not file_path.exists():
                print(f"🧬 Regenerating {core_file}...")
                self._regen_core_file(file_path)

    def _regen_core_file(self, file_path: Path):
        """Generate basic functional core file"""
        template = f"""
# Auto-Regenerated by NanoAI v2.5
# File: {file_path.name}

class {file_path.stem.title()}:
    def __init__(self):
        print("🧠 {{file_path.stem}} v2.5 ready")
    
    def process(self, input_text):
        return f"{{file_path.stem}}: {{input_text}}"

# Global instance
{file_path.stem} = {file_path.stem.title()}()
"""
        file_path.write_text(template.strip())

    def run(self):
        """Main bootstrap sequence"""
        print("🧠 NanoAI v2.5 Self-Bootstrapping...")
        
        # Phase 1: Dependencies
        self.auto_install_deps()
        
        # Phase 2: Core healing
        self.self_heal_core()
        
        # Phase 3: Launch
        try:
            from cli.shell import NanoShell
            shell = NanoShell()
            shell.start()
        except Exception as e:
            print(f"💥 Launch error: {e}")
            self._emergency_shell()

    def _emergency_shell(self):
        """Fallback interactive shell"""
        print("🔧 Emergency Shell")
        while True:
            cmd = input("nano> ").strip()
            if cmd in ["exit", "quit"]:
                break
            try:
                result = os.popen(cmd).read()
                print(result or "OK")
            except:
                print("Error")

if __name__ == "__main__":
    bootstrap = AutoBootstrap()
    bootstrap.run()